name: Build Repository

on:

  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  development-build:
    name: Development build with JDK 9
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 9
      - uses: skjolber/maven-cache-github-action@v3.1.2
        with:
          step: restore
      - run: mvn --batch-mode --update-snapshots verify
      - uses: skjolber/maven-cache-github-action@v3.1.2
        with:
          step: save
      - uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  release-build:
    name: Release build with JDK 9
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 9
      - uses: skjolber/maven-cache-github-action@v3.1.2
        with:
          step: restore
      - run: mvn -P release --batch-mode --update-snapshots verify
      - uses: skjolber/maven-cache-github-action@v3.1.2
        with:
          step: save
      - uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
